# Generated by Django 3.2.20 on 2023-09-07 07:25

from django.db import migrations
import geonode.people.models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0036_merge_20210706_0951'),
        ('myapp', '0002_ochadashboard_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileProxy',
            fields=[
            ],
            options={
                'verbose_name': 'HSDC User',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('people.profile',),
            managers=[
                ('objects', geonode.people.models.ProfileUserManager()),
            ],
        ),
    ]
