# Generated by Django 3.2.16 on 2023-04-26 10:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='earthquake_events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wkb_geometry', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('event_code', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=255)),
                ('dateofevent', models.DateTimeField()),
                ('magnitude', models.FloatField(blank=True, null=True)),
                ('depth', models.FloatField(blank=True, null=True)),
                ('shakemaptimestamp', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'earthquake_events',
                'managed': True,
            },
        ),
    ]
