# Generated by Django 3.2.16 on 2023-04-26 10:52

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='earthquake_shakemap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wkb_geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('event_code', models.CharField(blank=True, max_length=25)),
                ('shakemaptimestamp', models.BigIntegerField(blank=True, null=True)),
                ('grid_value', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'earthquake_shakemap',
                'managed': True,
            },
        ),
    ]
