# Generated by Django 3.2.20 on 2023-08-17 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geodb', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='earthquake_events',
        ),
    ]
